import express from "express";
import cors from "cors";
import helmet from "helmet";
import morgan from "morgan";
import authRoutes from "./routes/auth.routes.js";
import productRoutes from "./routes/product.routes.js";
import complaintRoutes from "./routes/complaint.routes.js";
import technicianRoutes from "./routes/technician.routes.js";
import { errorHandler, notFound } from "./middleware/error.middleware.js";

const app=express();
app.use(helmet());
app.use(cors());
app.use(express.json({limit:"1mb"}));
app.use(morgan("dev"));
app.get("/",(req,res)=>res.json({success:true,message:"Smart Electronic Service API is running"}));
app.get("/api/health",(req,res)=>res.json({success:true,status:"OK"}));
app.use("/api/auth",authRoutes);
app.use("/api/products",productRoutes);
app.use("/api/complaints",complaintRoutes);
app.use("/api/technicians",technicianRoutes);
app.use(notFound);
app.use(errorHandler);
export default app;
